version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - npm install
      - npm install -g webpack-cli

  build:
    commands:
      - npx tailwindcss -i ./public/assets/index.css -o ./public/output.css
      - webpack --config webpack.prod.js
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: 'public'
