version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

    commands:
      - npm install
      - npm install -D webpack-cli

  build:
    commands:
      - npx tailwindcss -i ./public/assets/index.css -o ./public/output.css
      - webpack --config webpack.prod.js

artifacts:
  files:
    - public/**/*