import React from "react";

export const Top25 = ({ response, setStage }) => {
  return (
    <section className="create-future-currency">
      <div className="overlay">
        <div className="container">
          <div className="main-content">
            <div className="row">
              <div className="col-lg-12">
                <div className="section-text text-center">
                  <h3>View Your Top 25</h3>
                  <p>
                    See the top 25 teams generated by your selection of
                    statistics.
                  </p>
                </div>
                <div className="row">
                  <div className="col-lg-12">
                    <div className="row justify-content-center">{response}</div>
                  </div>
                  <div className="col-lg-12">
                    <span className="btn-border">
                      <div
                        className="cmn-btn"
                        onClick={() => setStage(1)}
                        style={{ cursor: "pointer" }}
                      >
                        Go Back
                      </div>
                    </span>
                    <span className="btn-border">
                      <div
                        className="cmn-btn"
                        style={{ cursor: "pointer" }}
                      >
                        Next Step
                      </div>
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
