import React, { useEffect } from "react";

export const Top25 = ({ response, setStage }) => {
  useEffect(() => {
    window.scrollTo({top: 250, behavior: 'smooth'});
  }, [])

  const mockTableData = [
    {
      team: "Team 1",
      rank: 1,
      apRank: 25,
      diff: +24,
      color: "#00ff00",
    },
    {
      team: "Team 2",
      rank: 2,
      apRank: 2,
      diff: 0,
      color: "rgba(0,255,0,0)",
    },
    {
      team: "Team 3",
      rank: 3,
      apRank: 1,
      diff: -2,
      color: "rgba(255,0,0,0.2)",
    },
    {
      team: "Team 4",
      rank: 4,
      apRank: 8,
      diff: +4,
      color: "rgba(0,255,0,0.37)",
    },
    {
      team: "Team 5",
      rank: 25,
      apRank: 1,
      diff: -24,
      color: "rgb(255,0,0)",
    },
  ];

  return (
    <section className="create-future-currency">
      <div className="overlay">
        <div className="container">
          <div className="main-content">
            <div className="row">
              <div className="col-lg-12">
                <div className="section-text text-center">
                  <h3>View Your Top 25</h3>
                  <p>
                    See the top 25 teams generated by your selection of
                    statistics.
                  </p>
                </div>
                <div className="row">
                  <div className="col-lg-8">
                    <div className="section-text text-center">
                      <h5>Your Top 25</h5>
                    </div>
                    <Top25Table data={mockTableData} />
                  </div>
                  <div className="col-lg-4">
                    <div className="section-text text-center">
                      <h5>Biggest Movers</h5>
                    </div>
                  </div>
                  <div className="col-lg-12">
                    <span className="btn-border m-2">
                      <div
                        className="cmn-btn"
                        onClick={() => setStage(1)}
                        style={{ cursor: "pointer" }}
                      >
                        Go Back
                      </div>
                    </span>
                    <span className="btn-border m-2">
                      <div
                        className="cmn-btn"
                        style={{ cursor: "pointer" }}
                        onClick={() => setStage(3)}
                      >
                        Next Step
                      </div>
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

const Top25Table = ({ data }) => {
  return (
    <table className="table" style={{ color: "white" }}>
      <thead>
        <tr>
          <th scope="col">Rank</th>
          <th scope="col">Team</th>
          <th scope="col">AP Rank</th>
          <th scope="col">Difference</th>
        </tr>
      </thead>
      <tbody>
        {data.map((team) => (
          <tr>
            <th scope="row">{team.rank}</th>
            <td>{team.team}</td>
            <td>{team.apRank}</td>
            <td>{team.diff}</td>
            {/*<td style={{ backgroundColor: team.color }}>{team.diff}</td>*/}
          </tr>
        ))}
      </tbody>
    </table>
  );
};
